# Generated by Django 5.2.17 on 2026-08-31 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carta',
            name='juego',
            field=models.CharField(choices=[('Pokemon', 'Pokémon'), ('MTG', 'Magic: The Gathering'), ('Yugioh', 'Yu-Gi-Oh!'), ('Lorcana', 'Lorcana'), ('OnePiece', 'One Piece')], max_length=50, verbose_name='Juego TCG'),
        ),
    ]
